"""
This code setups UI for Main Window
"""

from PyQt4 import QtCore, QtGui
from vtk.qt4.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1271, 881)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qvtkWidget = QVTKRenderWindowInteractor(self.centralwidget)
        self.qvtkWidget.setObjectName(_fromUtf8("qvtkWidget"))
        self.gridLayout.addWidget(self.qvtkWidget, 2, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        # a figure instance to plot on
        self.figure = Figure()
        # this is the Canvas Widget that displays the `figure`
        # it takes the `figure` instance as a parameter to __init__
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, MainWindow)

        # this is the Navigation widget
        # it takes the Canvas widget and a parent.
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        #self.horizontalLayout_1.setSpacing(6)
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
       
        
        self.radioButton_hist = QtGui.QRadioButton(self.canvas)
        self.radioButton_hist.setObjectName(_fromUtf8("radioButton_hist"))
        
        #self.horizontalSlider_min = QtGui.QSlider(self.canvas)
        #self.horizontalSlider_min.setOrientation(QtCore.Qt.Horizontal)
        #self.horizontalSlider_min.setObjectName(_fromUtf8("horizontalSlider_min"))
       
        #self.horizontalSlider_max = QtGui.QSlider(self.canvas)
        #self.horizontalSlider_max.setOrientation(QtCore.Qt.Horizontal)
        #self.horizontalSlider_max.setObjectName(_fromUtf8("horizontalSlider_max"))
        self.min = QtGui.QLineEdit(self.canvas)#change it min_linedit
        self.min.setGeometry(QtCore.QRect(50, 50, 71, 20))
        self.max = QtGui.QLineEdit(self.canvas)
        self.max.setGeometry(QtCore.QRect(100, 170, 71, 20))
        self.setRange= QtGui.QPushButton(self.canvas)
        self.setRange.setObjectName(_fromUtf8("Set Range"))
        
        self.layout = QtGui.QVBoxLayout(self.widget_2)
        self.layout.addWidget(self.canvas)
        self.layout.addWidget(self.toolbar)
        self.layout.addWidget(self.radioButton_hist)
        #self.layout.addWidget(self.horizontalSlider_min)
        #self.layout.addWidget(self.horizontalSlider_max)
        self.horizontalLayout_1.addWidget(self.radioButton_hist)
        self.horizontalLayout_1.addWidget(self.min)
        self.horizontalLayout_1.addWidget(self.max)
        self.horizontalLayout_1.addWidget(self.setRange)
        self.layout.addLayout(self.horizontalLayout_1)
	#self.layout.addWidget(self.max)
	#self.layout.addWidget(self.setRange)    
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.tableWidget = QtGui.QTableWidget(self.widget_3)
        self.tableWidget.setGeometry(QtCore.QRect(100, 50, 161, 111))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.pushButton_8 = QtGui.QPushButton(self.widget_3)
        self.pushButton_8.setGeometry(QtCore.QRect(270, 60, 61, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.widget_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 170, 71, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.widget_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 170, 71, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_9 = QtGui.QPushButton(self.widget_3)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 170, 61, 21))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.widget_3, 1, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_10 = QtGui.QPushButton(self.frame_2)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_13 = QtGui.QPushButton(self.frame_2)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_4 = QtGui.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_12 = QtGui.QPushButton(self.frame_2)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.verticalLayout.addWidget(self.pushButton_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.saveImage_pushButton = QtGui.QPushButton(self.frame_2)
        self.saveImage_pushButton.setObjectName(_fromUtf8("saveImage_pushButton"))
        self.horizontalLayout_3.addWidget(self.saveImage_pushButton)
        self.loadImage_pushButton = QtGui.QPushButton(self.frame_2)
        self.loadImage_pushButton.setObjectName(_fromUtf8("loadImage_pushButton"))
        self.horizontalLayout_3.addWidget(self.loadImage_pushButton )
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.radioButton_3 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_3)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.pushButton_2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.frame_3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit.setText("300")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_3 = QtGui.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_3)
        self.radioButton_6 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.verticalLayout.addWidget(self.radioButton_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.pushButton_11 = QtGui.QPushButton(self.frame_2)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_15 = QtGui.QPushButton(self.frame_2)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.pushButton_14 = QtGui.QPushButton(self.frame_2)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalSlider = QtGui.QSlider(self.frame_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_4 = QtGui.QRadioButton(self.frame)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.frame)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_4.setText("10")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_5.setText("16")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_7 = QtGui.QPushButton(self.frame_2)
        self.pushButton_7.setWhatsThis(_fromUtf8(""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout.addWidget(self.pushButton_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_2)
        self.pushButton_5.setWhatsThis(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 8)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AnuTom", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Intensity", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Opacity", None))
        self.pushButton_8.setToolTip(_translate("MainWindow", "Select point from the table to remove", None))
        self.pushButton_8.setText(_translate("MainWindow", "Remove", None))
        
        self.radioButton_hist.setToolTip(_translate("MainWindow", "For changing histogram mode", None))
        self.radioButton_hist.setText(_translate("MainWindow", "Setting Range", None))
        self.min.setToolTip(_translate("MainWindow", "to get min value", None))
        self.min.setText(_translate("MainWindow", "min", None))
        
        
        self.lineEdit_2.setToolTip(_translate("MainWindow", "Enter the gray value (x-axis)", None))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "Enter the opacity value (y-axis)", None))
        self.pushButton_9.setToolTip(_translate("MainWindow", "Adds the point to Opacity function", None))
        self.pushButton_9.setText(_translate("MainWindow", "Add", None))
        self.label_2.setText(_translate("MainWindow", "Modify Opacity Function", None))
        self.setRange.setToolTip(_translate("MainWindow", "sets the range", None))
        self.setRange.setText(_translate("MainWindow", "Set Range", None))
        self.pushButton.setToolTip(_translate("MainWindow", "Load the input images", None))
        self.pushButton.setText(_translate("MainWindow", "Load Image Stack", None))
        self.pushButton_10.setToolTip(_translate("MainWindow", "Back to default with same loaded image stack", None))
        self.pushButton_10.setText(_translate("MainWindow", "Reset Volume", None))
        self.pushButton_13.setToolTip(_translate("MainWindow", "Back to default camera view", None))
        self.pushButton_13.setText(_translate("MainWindow", "Reset Camera", None))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Change the color map of rendered volume", None))
        self.pushButton_4.setText(_translate("MainWindow", "Change Color Map", None))
        self.pushButton_12.setToolTip(_translate("MainWindow", "Change Background color of render window", None))
        self.pushButton_12.setText(_translate("MainWindow", "Change BG Color", None))
        self.saveImage_pushButton.setText(_translate("MainWindow", "Save Image", None))
        #set tool tip
        self.loadImage_pushButton.setText(_translate("MainWindow", "Load Image", None))
        #set tool tip
        self.radioButton_3.setToolTip(_translate("MainWindow", "For Multiple orthogonal clipping", None))
        self.radioButton_3.setText(_translate("MainWindow", "Clipping Box", None))
        self.radioButton_2.setToolTip(_translate("MainWindow", "For single arbitary plane clipping and slicing", None))
        self.radioButton_2.setText(_translate("MainWindow", "Plane Widget", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Clip using plane of Plane Widget", None))
        self.pushButton_2.setText(_translate("MainWindow", "Clip", None))
        self.label.setText(_translate("MainWindow", "Slice Resolution:", None))
        self.lineEdit.setToolTip(_translate("MainWindow", "Enter the resolution of Slice cutted by Plane Widget", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Set the resolution of Slice cutted by Plane Widget", None))
        self.pushButton_3.setText(_translate("MainWindow", "Set", None))
        self.radioButton_6.setToolTip(_translate("MainWindow", "For orthogonal slicing along the principle axes", None))
        self.radioButton_6.setText(_translate("MainWindow", "Orthogonal Slicing", None))
        self.label_6.setText(_translate("MainWindow", "Align to:  ", None))
        self.pushButton_11.setToolTip(_translate("MainWindow", "Align plane to x axis", None))
        self.pushButton_11.setText(_translate("MainWindow", "x", None))
        self.pushButton_15.setToolTip(_translate("MainWindow", "Align plane to y axis", None))
        self.pushButton_15.setText(_translate("MainWindow", "y", None))
        self.pushButton_14.setToolTip(_translate("MainWindow", "Align plane to z axis", None))
        self.pushButton_14.setText(_translate("MainWindow", "z", None))
        self.horizontalSlider.setToolTip(_translate("MainWindow", "Position of plane", None))
        self.label_7.setText(_translate("MainWindow", "Visible Objects : ", None))
        self.radioButton.setToolTip(_translate("MainWindow", "Toggle Outline", None))
        self.radioButton.setText(_translate("MainWindow", "Outline", None))
        self.radioButton_4.setToolTip(_translate("MainWindow", "Toggle Volume visibility", None))
        self.radioButton_4.setText(_translate("MainWindow", "Volume Visibility", None))
        self.radioButton_5.setToolTip(_translate("MainWindow", "Toggle Slice Vibility", None))
        self.radioButton_5.setText(_translate("MainWindow", "Slice Visibility", None))
        self.label_3.setText(_translate("MainWindow", "Record for :", None))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "Enter time in seconds for which you want to record the interaction with render window", None))
        self.label_4.setText(_translate("MainWindow", "secs         at", None))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "Enter frame rate", None))
        self.label_5.setText(_translate("MainWindow", "frames/sec", None))
        self.pushButton_7.setToolTip(_translate("MainWindow", "Records the action performed with interactor", None))
        self.pushButton_7.setText(_translate("MainWindow", "Record", None))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Saves image of the renderer window", None))
        self.pushButton_5.setText(_translate("MainWindow", "Snapshot", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

